# Generated by Django 3.2.12 on 2022-06-28 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('owner', '擁有者'), ('maintainer', '維護者'), ('guest', '訪客')], default='guest', max_length=20),
        ),
    ]
