# Generated by Django 4.0.4 on 2022-05-12 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('98e9d826-7543-437d-8a3f-d6e0c2035884'), editable=False, primary_key=True, serialize=False),
        ),
    ]
