# Generated by Django 4.0.4 on 2022-05-12 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_password_alter_account_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b4248d3a-7ed7-4e27-80a3-7931056221c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
