# Generated by Django 3.2.12 on 2022-06-17 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_password_alter_account_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3fa9b780-ccd0-4784-afcc-a9f18543f493'), editable=False, primary_key=True, serialize=False),
        ),
    ]
